In [1]:
l = [3213213, 213123, 1233124512, 12312321]

In [2]:
l

[3213213, 213123, 1233124512, 12312321]

In [3]:
import numpy as np #Numby array can't havve different types on a numpy array (like Vector in R)

In [5]:
a = np.array(l)

In [6]:
a

array([   3213213,     213123, 1233124512,   12312321])

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([12, 455, 63.3, True, "abc"])

In [9]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [10]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
l.pop()

12312321

In [12]:
l

[3213213, 213123, 1233124512]

In [13]:
a.mean()

312215792.25

In [14]:
b = np.array([12, "s", False, True, "abc"])

In [15]:
b

array(['12', 's', 'False', 'True', 'abc'], dtype='<U21')

In [16]:
b = np.array([False, True, "abc"])

In [17]:
b

array(['False', 'True', 'abc'], dtype='<U5')

In [18]:
a

array([   3213213,     213123, 1233124512,   12312321])

In [19]:
a[0:2]

array([3213213,  213123])

In [20]:
a

array([   3213213,     213123, 1233124512,   12312321])

In [21]:
a

array([   3213213,     213123, 1233124512,   12312321])

In [22]:
a

array([   3213213,     213123, 1233124512,   12312321])

In [23]:
a

array([   3213213,     213123, 1233124512,   12312321])

In [24]:
 #Slicing in Numpy Array does not create a new copy but a view of that array(same reference to the same object)

In [25]:
b = a[2:4]

In [26]:
b

array([1233124512,   12312321])

In [27]:
b[:]=111111

In [28]:
b

array([111111, 111111])

In [29]:
a

array([3213213,  213123,  111111,  111111])