In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [2]:
import numpy as np

In [16]:
profit_per_month = np.array(revenue) - np.array(expenses)

In [7]:
profit_per_month   # Revenue - Expenses

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [8]:
profit_per_month_after_tax = profit_per_month * 0.7

In [9]:
profit_per_month_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [10]:
profit_margin_per_month = profit_per_month_after_tax / revenue

In [87]:
profit_margin_per_month

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [17]:
mean_year_profit_after_tax = profit_per_month_after_tax.mean()

In [18]:
mean_year_profit_after_tax

1750.6813333333332

In [52]:
filtered_months = [] # where the profit after tax was fgreater than the mean for the year

In [128]:
filtered_months =  profit_per_month_after_tax > mean_year_profit_after_tax;
profit_good_months = profit_per_month_after_tax[filtered_months]
good_months

array([1765.869, 5085.668, 5747.385, 2761.479, 2329.873, 8140.678])

In [148]:
print(profit_per_month_after_tax)
filtered_months = profit_per_month_after_tax > mean_year_profit_after_tax;
profit_bad_months = profit_per_month_after_tax[filtered_months]
profit_bad_months

[ 1765.869  1337.973 -2595.453 -2040.017  -419.944  5085.668  5747.385
  2761.479  2329.873 -1567.055   461.72   8140.678]


array([1765.869, 5085.668, 5747.385, 2761.479, 2329.873, 8140.678])

In [163]:
filtered_months = profit_per_month_after_tax == profit_per_month_after_tax.max();
profit_best_month = profit_per_month_after_tax[filtered_months]
best_month = np.where(profit_per_month_after_tax == profit_best_month)[0][0] + 1
best_month

12

In [162]:
filtered_months = profit_per_month_after_tax == profit_per_month_after_tax.min();
profit_worst_month = profit_per_month_after_tax[filtered_months]
worst_month = np.where(profit_per_month_after_tax == profit_worst_month)[0][0] + 1
worst_month

3